apiVersion: v1
kind: Pod
metadata:
  name: appd-snmp-gateway
spec:
  containers:
  - name: appd-snmp-gateway
    image: johnsoutherland/appdynamics-web-rest-to-snmp-trap:1.5
    imagePullPolicy: Always
    volumeMounts:
    - name: my-config
      mountPath: /config
  volumes:
  - name: my-config
    configMap:
      name: snmp-config
